[WIP] ChatSpaceのデータベース設計
1ruru/chat-space pull request #4
Opened 2019-03-16 09:01 UTC by 1ruru

Delete unnecessary writing
Add users_groups table & association
Add users table & association
Add groups table & association
Add messages table & association

2019-03-16 09:03 UTC, 1ruru commented
#WHAT
ChatSpaceのデータベース設計をREADME.mdに記述

#WHY
ChatSpace開発においてデータベース設計が必須であるから

2019-03-16 09:14 UTC, 1ruru commented
すみません、indexつけ忘れてたので修正しました。

2019-03-16 09:47 UTC, yuki-uchida requested changes

2019-03-16 09:47 UTC, yuki-uchida commented on README.md
> +| user_id  | int  | null: false, foreign_key: true |
外部キーの場合にはrefference型としましょう

2019-03-16 09:47 UTC, yuki-uchida commented on README.md
> +| body     | text   | null: false                    |
画像だけでも投稿できるようにしましょう

2019-03-16 10:00 UTC, 1ruru commented on README.md
> +| user_id  | int  | null: false, foreign_key: true |
ご連絡ありがとうございます。修正いたしました。

2019-03-16 10:00 UTC, 1ruru commented on README.md
> +| body     | text   | null: false                    |
ご連絡ありがとうございます。修正いたしました。

2019-03-17 06:41 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-03-17 06:42 UTC, 1ruru commented
今からhamlを導入するみたいなので、
修正完了ということでマージしてもよろしいでしょうか？

2019-03-17 06:42 UTC, 1ruru commented
ありがとうございました。

2019-03-17 06:43 UTC, merged